### ISSUE TITLE
Auth guest check for AJAX does not work

### ISSUE THREAD

**Issue by progmars** [subfission/cas#12]
I tried to use this in an ajax app and noticed that it always throws Unauthorized, 401. I found the code in CASAuth.php:

```
    if ($this->auth->guest())
    {
        if ($request->ajax())
        {
            return response('Unauthorized.', 401);
        }
        $cas = app('cas');
        $cas->authenticate();
    }
```

Debugging to see how auth could be something else than a guest, I found the single place where user data is stored:

```
Session::put('cas_user', $this->remoteUser);
```

but there are no other places where `cas_user` is processed. Of course, Laravel Auth does not know anything about it and therefore there is no point to check for auth->guest() - it will always be true and you will always end up aborting AJAX requests or requesting auth from phpCAS.

I guess, if you stored `cas_user` in Session then you should check it in this handle() call to find out if there is valid auth session.

**Comment by subfission** [comment]
Ok, so a few things: 
- phpCas uses a default session called CASAuth that is independent of Laravel.  I needed a simple Laravel way of determining if the session was created hence the 'cas_user'.
- If you need a Laravel style hook, the cas_user is the goto for that.  This allows for the user to disconnect from CAS, yet still be authenticated into your project.  If you don't require it, don't use it.
- Also, this plugin does NOT manage authorization.  Meaning you need to create your own authorization rules.  I created middleware that queries the CAS plugin and then determines if the user should have access.  My project requires they CAS Auth and then have permission to access the app.
  
  Your issue is that after completing the CAS auth your user is still a guest.  _That is not an issue with the plugin._  Once you build your middleware, you may want your own guard too, you can use that location to hook the CAS Auth.

I also created a custom Guard (so the one below is not the laravel default)

Sample middleware:

``` php
class Authenticate {

    /**
     * The Guard implementation.
     *
     * @var Guard
     */
    protected $auth;

    /**
     * Create a new filter instance.
     *
     * @param  Guard $auth
     */
    public function __construct(Guard $auth)
    {
        $this->auth = $auth;
    }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if ( $this->auth->guest() )
        {
            try
            {
                $user = $this->checkCASUser(Cas::user());
            } catch ( ModelNotFoundException $e )
            {
                $user = false;
            }
            if ( ! $user || ! Auth::attempt(['id' => $user->id, 'acc_id' => $user->acc_id]) )
            {
                if ( $request->ajax() )
                {
                    return response('Unauthorized.', 401);
                } else
                {
                    return redirect()->guest('/');
                }

            }
        }

        if ( $restrictions = $this->getRestrictions($request) )
        {
            if ( ! $this->handleRestrictions($restrictions) )
            {
                return redirect()->route('home');
            }
        }

        return $next($request);
    }
```

**Comment by progmars** [comment]
Thanks, this makes sense. At the end I created my own middleware anyway. 

The confusion was because I imagined that CASAuth would work "out-of-the-box" and that it is already integrated with Laravel's Guard or uses its own session values (`cas_user`) to see if the user is authenticated or not instead of relying upon Laravel's guard which is not initialized at that point.

**Comment by subfission** [comment]
No problem!  Let me know if you find anything else and feel free to make feature requests.
