### ISSUE TITLE
CAS Logout not reflecting

### ISSUE THREAD

**Issue by senthilkumar-rk** [subfission/cas#24]
Hi,

I want to say big thanks for this cas plugin.

Everything is working fine, but i have faced only one problem. If we signout in "CAS" website our laravel  does not logout if i did any action in application.. Could you please update any idea for this.

Thanks for your help.

Regards,
Sen

**Comment by subfission** [comment]
Hi Sensri, the reason for this is the included example middleware.  If you would like for cas to authenticate on each page request, simply create a middleware, very similar to the included one, but without the line:

`if ( ! session('cas_user') ) {`

Or you can just change that entire method to:

```
public function handle($request, Closure $next)
{
    if ( ! $this->cas->isAuthenticated()  ) {
        if ($request->ajax()) {
            return response('Unauthorized.', 401);
        }
        $this->cas->authenticate();

        // Add session variable to store cas user
        session()->put('cas_user', $this->cas->user());
    }
    return $next($request);
}
```

The purpose of the middeware was just an example as everyone has their own implementation for cas.  If enough people want it, I can also add a configuration option to force CAS auth checking on each request.

On my setup, the server will respond to each application when the user signs out of the CAS server with a ajax call.  This is then captured by my application via the logout route, and kills the user session. Your implementation may very.

**Comment by senthilkumar-rk** [comment]
Thanks for your reply and solution... Let me check and update you....

Once again thank you so much for your support...

Regards,
Senthilkumar

**Comment by subfission** [comment]
Check into the latest update as well.  I implemented some new features that may be useful to you for redirecting.

**Comment by senthilkumar-rk** [comment]
Thanks for your update and help..

As per your instruction, i have updated Middleware code, but still i got same problem. If "CAS" logged out, but our laravel application not logouting. 

If you have any suggestion, please let me know. 

Regards,
Senthilkumar

**Comment by subfission** [comment]
Hi Senthilkumar,

Please enable both:
`'cas_debug'    'cas_verbose_errors'`
...and post the results of your log file.  This will give us a better understanding of what is happening under the hood.

**Comment by senthilkumar-rk** [comment]
Thanks for your quick response.

Kindly check attached log file and let me know the status. 

Note : I have checked your code "_wasPreviouslyAuthenticated" method, i think we didn't validate whether CAS server ticket is empty or not. 

But i'm not sure about this function. Kindly check and do the needful. 

[phpCAS.txt](https://github.com/subfission/cas/files/256624/phpCAS.txt)

**Comment by subfission** [comment]
Yep, we are closer to the issue now.  It looks like you are doing redundant authentication checks... This could mean you are not capturing the authenticated session.  Still we have too many variables that prevent us from properly diagnosing the issue.

To break this down, we know:
- You are able to communicate with your cas server.
- You received the authenticated ticket and the user.
- phpCAS has acknowledged your user is stored in the session.
- Your user is being redirected to http://localhost/dgo/hrms-design/
- ...No data recorded past this part...

With the above, my guess is that you have a _cas.auth_ middleware on that page.  Remember, when you log out of CAS, unless you specify a logout redirect URL, it will return you back to the page from which you came.  Usually, I have a 'You have logged out successfully' splash page that destroys all remaining Laravel sessions (in a controller).

If you want to link me to your Git repo for your app, I can dive deeper.  Otherwise, I recommend adding breaks in your code and dumping session variables to see what is failing.

**Comment by senthilkumar-rk** [comment]
Thanks for update. Since my client not provide privileges to access code for you. 

If possible, can you please explain me how to achieve this.

Regards,
Senthilkumar

**Comment by subfission** [comment]
No problem SenthiKumar,

You will need a route for logout requests coming from your CAS.  That should point at a controller, usually auth/logout or something similar, that contains your session cleanup methods: session()->flush() && redirect()->route('unathenticated.home').

I do not see this as being an issue with the plugin code, so I will close this issue.
