### ISSUE TITLE
Single logout not working

### ISSUE THREAD

**Issue by vaggelis2018** [subfission/cas#61]
Hello and thanks for your great package.
I have built an app and everything works great except single logout.
I excluded from csrf protection and modified the /logout endpoint to look like this
```
if( cas()->isAuthenticated() ) {
                cas()->logout();
            } else {
                redirect('/');
            }
```

Note that i am not setting any local session and i have tried both back and front channels from cas server. Also i am not getting any errors on my logs just that the cas has passed from here when i add this line to the controller
```
Log::info('cas passed from here');
```
I have already checked issues #25 and #30 and i wans't able to find a solution.
Am i doing something wrong?

**Comment by subfission** [comment]
First thing is to enable verbose logging.  You can do this from your env file or config.  I would check to see if you are automatically re-authenticating with your CAS server.

Additionally, the CAS server will respond with a post-back logout request.  You will want to make sure you capture this event and kill the session on that event.  I usually do this in a custom middleware.

If you are still struggling after reviewing the verbose logs, post them in here with your middleware.

**Comment by vaggelis2018** [comment]
I ll check it as soon as possible and i ll let you know.

**Comment by vaggelis2018** [comment]
I have a question man. The post request is from server to server. How i should find the correct session to delete? Do i have to use database or redis or something else to store sessions so i ll be able to find or delete session? Also i saw in the drupal module they store tickets in db. Does this help?

**Comment by subfission** [comment]
Personally, I think the Drupal methods are slow and poorly designed.  I prefer to cache the session into Redis or an in-memory, key-value store as you get a nice performance boost.  I want my pages executed sub-millisecond and ready to be sent back to the user.  The network aspects will always be a bottleneck if you have a high efficiency design.

Ultimately, these are all developer design decisions, but you do _not_ usually want to query the CAS server every time someone makes a page request.  Once the user has CAS auth'ed, cache the auth for a short period of time, then refresh the cache if a new page is requested.  If the period of time has expired, delete the session and force the user to re-auth.  If you have a high volume of sessions stuck, use a job runner to auto-clear expired sessions from your key store.

For mapping a CAS user to a App user, I usually implement an extension to the auth driver.  I check my CAS user for a matching credential in a user table and if found, allow access and create an authenticated & authorized session that I cache.  This plugin does not manage how a user is authenticated and authorized to your App since everyone has their own project requirements.
