### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by ambariss7** [subfission/cas#63]
Hello. I'm new to Laravel, so please be easy on me. I'm working on my first app and I need to implement CAS Authentication..
please... give me easy tutorial for implementation

**Comment by subfission** [comment]
First places I'd recommend are Laracasts and the the Laravel docs on services and plugins.  Then, I would check the wiki for this plugin.  This is not really an entry level plugin since you will need several customizations to get this working with your own SSO server.  Usually you will want your own middleware solutions and custom kernel driver for mapping SSO accounts to your application users.  Hopefully, this helps you get started.

**Comment by subfission** [comment]
I would advise a good starting point is the Wiki.  If you have questions, feel free to ask after reviewing.
