### ISSUE TITLE
DOMDocument::loadXML(): Empty string supplied as input

### ISSUE THREAD

**Issue by ashish-ucsb** [subfission/cas#71]
Hello,

First, I'd like to thank subfission & everyone who has contributed to this project. This package works like magic. However, I am running into `DOMDocument::loadXML(): Empty string supplied as input` when I make `cas_enable_saml` to `true`. I am new to authentication & php overall. 
And I don't know how to even start to debug this. 
.
![image](https://user-images.githubusercontent.com/46073809/63415425-9604c200-c3b2-11e9-90de-36f9450ee353.png)
& as you can see in arguments, it is empty
![image](https://user-images.githubusercontent.com/46073809/63415470-a6b53800-c3b2-11e9-8378-99e804fb229d.png)
This is my config file
![image](https://user-images.githubusercontent.com/46073809/63415659-eda32d80-c3b2-11e9-8cee-97060b1898eb.png)

All help is appreciated. Thank you.

**Comment by subfission** [comment]
Hello Santa Barbara!  I'm jealous of your good weather.

It appears UCSB only supports **CAS protocol version 2**.  Not **SAML 1.1**.

https://secure.identity.ucsb.edu/inside/doku.php/sso_home:cas_php

You will need to set `cas_enable_saml` to `false`.

Try that first.  Otherwise, I'd reach out to your SSO support services and have them verify your CAS settings as every university implements their CAS server differently.

If both of these don't work, we can look through your logs.

**Comment by ashish-ucsb** [comment]
Hello subfission,
weather here is AMAZING !!
Thanks for taking time to check in on the issue.
SAML when set to false, works like charm. Sorry for not mentioning it in the post.

**Comment by subfission** [comment]
No problem!
